#ifndef MODULE_GRAPHIC_GLOBAL_H
#define MODULE_GRAPHIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_GRAPHIC_LIBRARY)
#  define MODULE_GRAPHIC_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_GRAPHIC_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_GRAPHIC_GLOBAL_H
