#ifndef MODULE_FMU_LOGIC_GLOBAL_H
#define MODULE_FMU_LOGIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_MACRO_LOGIC_LIBRARY)
#  define MODULE_LOGIC_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_FMU_LOGIC_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_FMU_LOGIC_GLOBAL_H
