#ifndef FBSFBASEMODEL_GLOBAL_H
#define FBSFBASEMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FBSFBASEMODEL_LIBRARY)
#  define FBSFBASEMODEL_EXPORT Q_DECL_EXPORT
#else
#  define FBSFBASEMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // FBSFBASEMODEL_GLOBAL_H
